import { Injectable, BadRequestException, NotFoundException } from '@nestjs/common';
import { PrismaService, JournalEntryStatus, Prisma } from '@erp/database';
import { CreateJournalEntryDto } from './dto/create-journal-entry.dto';
import { JournalEntryFilterDto } from './dto/journal-entry-filter.dto';

@Injectable()
export class JournalEntriesService {
  constructor(private prisma: PrismaService) {}

  async create(dto: CreateJournalEntryDto, companyId: string, userId: string) {
    await this.validateJournalEntry(dto);

    const entryNumber = await this.generateEntryNumber(companyId);

    return this.prisma.journalEntry.create({
      data: {
        entryNumber,
        date: dto.date,
        description: dto.description,
        reference: dto.reference,
        status: JournalEntryStatus.DRAFT,
        totalDebit: dto.lines.reduce((sum, l) => sum + l.debit, 0),
        totalCredit: dto.lines.reduce((sum, l) => sum + l.credit, 0),
        companyId,
        branchId: dto.branchId,
        createdById: userId,
        sourceModule: dto.sourceModule,
        sourceId: dto.sourceId,
        lines: {
          create: dto.lines.map((line, index) => ({
            accountId: line.accountId,
            description: line.description,
            debit: line.debit,
            credit: line.credit,
            sortOrder: line.sortOrder ?? index + 1,
          })),
        },
      },
      include: {
        lines: {
          include: { account: true },
          orderBy: { sortOrder: 'asc' },
        },
      },
    });
  }

  async findAll(companyId: string, filter?: JournalEntryFilterDto) {
    const where: Prisma.JournalEntryWhereInput = { companyId };

    if (filter) {
      if (filter.fromDate || filter.toDate) {
        where.date = {};
        if (filter.fromDate) where.date.gte = filter.fromDate;
        if (filter.toDate) where.date.lte = filter.toDate;
      }
      if (filter.status) where.status = filter.status;
      if (filter.search) {
        where.OR = [
          { entryNumber: { contains: filter.search } },
          { description: { contains: filter.search } },
          { reference: { contains: filter.search } },
        ];
      }
    }

    return this.prisma.journalEntry.findMany({
      where,
      include: {
        lines: {
          include: { account: true },
          orderBy: { sortOrder: 'asc' },
        },
        createdBy: {
          select: { id: true, nameAr: true, nameEn: true },
        },
        postedBy: {
          select: { id: true, nameAr: true, nameEn: true },
        },
      },
      orderBy: { date: 'desc' },
    });
  }

  async findOne(id: string, companyId: string) {
    const entry = await this.prisma.journalEntry.findFirst({
      where: { id, companyId },
      include: {
        lines: {
          include: { account: true },
          orderBy: { sortOrder: 'asc' },
        },
        createdBy: {
          select: { id: true, nameAr: true, nameEn: true },
        },
        postedBy: {
          select: { id: true, nameAr: true, nameEn: true },
        },
      },
    });

    if (!entry) {
      throw new NotFoundException('قيد اليومية غير موجود');
    }

    return entry;
  }

  async post(id: string, companyId: string, userId: string) {
    const entry = await this.findOne(id, companyId);

    if (entry.status !== JournalEntryStatus.DRAFT) {
      throw new BadRequestException('يمكن ترحيل القيود في حالة مسودة فقط');
    }

    return this.prisma.journalEntry.update({
      where: { id },
      data: {
        status: JournalEntryStatus.POSTED,
        postedById: userId,
        postedAt: new Date(),
      },
      include: {
        lines: {
          include: { account: true },
          orderBy: { sortOrder: 'asc' },
        },
      },
    });
  }

  async reverse(id: string, companyId: string, userId: string) {
    const entry = await this.findOne(id, companyId);

    if (entry.status !== JournalEntryStatus.POSTED) {
      throw new BadRequestException('يمكن عكس القيود المرحلة فقط');
    }

    const reversedLines = entry.lines.map((line) => ({
      accountId: line.accountId,
      description: `عكس: ${line.description || entry.description}`,
      debit: line.credit,
      credit: line.debit,
    }));

    const reverseEntryNumber = await this.generateEntryNumber(companyId);

    return this.prisma.journalEntry.create({
      data: {
        entryNumber: reverseEntryNumber,
        date: new Date(),
        description: `عكس قيد ${entry.entryNumber}: ${entry.description}`,
        status: JournalEntryStatus.POSTED,
        totalDebit: entry.totalCredit,
        totalCredit: entry.totalDebit,
        companyId,
        createdById: userId,
        postedById: userId,
        postedAt: new Date(),
        isAutoGenerated: true,
        sourceModule: 'journal-entries',
        sourceId: id,
        lines: {
          create: reversedLines.map((line, index) => ({
            accountId: line.accountId,
            description: line.description,
            debit: line.debit,
            credit: line.credit,
            sortOrder: index + 1,
          })),
        },
      },
      include: {
        lines: {
          include: { account: true },
          orderBy: { sortOrder: 'asc' },
        },
      },
    });
  }

  async cancel(id: string, companyId: string) {
    const entry = await this.findOne(id, companyId);

    if (entry.status !== JournalEntryStatus.DRAFT) {
      throw new BadRequestException('يمكن إلغاء القيود في حالة مسودة فقط');
    }

    return this.prisma.journalEntry.update({
      where: { id },
      data: { status: JournalEntryStatus.CANCELLED },
    });
  }

  private async validateJournalEntry(dto: CreateJournalEntryDto) {
    if (!dto.lines || dto.lines.length < 2) {
      throw new BadRequestException('يجب إضافة طرفين على الأقل للقيد');
    }

    const totalDebit = dto.lines.reduce((sum, l) => sum + l.debit, 0);
    const totalCredit = dto.lines.reduce((sum, l) => sum + l.credit, 0);

    if (Math.abs(totalDebit - totalCredit) > 0.001) {
      throw new BadRequestException(
        `المجموع غير متوازن: المدين (${totalDebit}) ≠ الدائن (${totalCredit})`,
      );
    }

    for (const line of dto.lines) {
      if (line.debit > 0 && line.credit > 0) {
        throw new BadRequestException(
          'لا يمكن أن يحتوي السطر على قيم مدين ودائن معاً',
        );
      }
      if (line.debit === 0 && line.credit === 0) {
        throw new BadRequestException('يجب إدخال قيمة مدين أو دائن للسطر');
      }

      const account = await this.prisma.account.findUnique({
        where: { id: line.accountId },
      });
      if (!account) {
        throw new BadRequestException(`الحساب ${line.accountId} غير موجود`);
      }
      if (!account.isDetail) {
        throw new BadRequestException(
          `لا يمكن الترحيل لحساب ${account.nameAr} فهو ليس حساب تفصيلي`,
        );
      }
      if (!account.allowManualEntry) {
        throw new BadRequestException(
          `لا يمكن إضافة قيود يدوية لحساب ${account.nameAr}`,
        );
      }
    }
  }

  private async generateEntryNumber(companyId: string): Promise<string> {
    const year = new Date().getFullYear();
    const lastEntry = await this.prisma.journalEntry.findFirst({
      where: { companyId },
      orderBy: { createdAt: 'desc' },
    });

    const nextNumber = lastEntry
      ? parseInt(lastEntry.entryNumber.split('-')[2] || '0', 10) + 1
      : 1;

    return `JE-${year}-${String(nextNumber).padStart(5, '0')}`;
  }
}
